/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'smazumder' at '5/17/14 1:25 AM' with Gradle 1.12
 *
 * @author smazumder, @date 5/17/14 1:25 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
